import Phaser from 'phaser';
import { Player } from '../entities/Player.js';
import { StreetRat } from '../entities/StreetRat.js';
import { Cockroach } from '../entities/Cockroach.js';
import { FrenchFries } from '../entities/FrenchFries.js';
import { getStage } from '../data/stages.js';
import { SoundManager } from '../audio/SoundManager.js';
import { sealFinalSection, showStageTransition } from '../utils/stageTransition.js';

const FRIES_HEAL = 25;
const WAVE_CLEAR_TEXT_MS = 1500;
const WAVE_ADVANCE_DELAY_MS = 1000;
const STARTING_LIVES = 3;
const RAT_KILL_SCORE = 100;
const GET_UP_TEXT_MS = 1000;

// Scrolling-stage world geometry. World is three 1536-wide tiles displayed
// at 576 tall. Player is constrained to the sidewalk band (Y 380-490) and
// the full world width (X 0-4608).
const WORLD_WIDTH = 4608;
const WORLD_HEIGHT = 576;
const BG_TILE_WIDTH = 1536;
const BG_TILE_HEIGHT = 576;
const SIDEWALK_Y_MIN = 380;
const SIDEWALK_Y_MAX = 490;
const PLAYER_SPAWN_X = 200;
const PLAYER_SPAWN_Y = 440;
const CAMERA_VIEW_HALF = 512; // half of 1024 canvas width
const CAMERA_PAN_MS = 400;
const CAMERA_LERP_X = 0.15;
const CAMERA_DEADZONE_W = 200;

export class BootScene extends Phaser.Scene {
  constructor() {
    super('BootScene');
  }

  preload() {
    // Which kid did the player pick in CharacterSelect? Fall back to aiden
    // if BootScene was started directly (e.g. in dev without going through
    // the select screen).
    const chosenKey = this.registry.get('chosenChar') ?? 'aiden';
    this.chosenKey = chosenKey;

    // Player: load only the chosen kid's 6 pose sprites.
    this.load.image(`${chosenKey}-idle`, `./assets/sprites/${chosenKey}-idle.png`);
    this.load.image(`${chosenKey}-walk-1`, `./assets/sprites/${chosenKey}-walk-1.png`);
    this.load.image(`${chosenKey}-walk-2`, `./assets/sprites/${chosenKey}-walk-2.png`);
    this.load.image(`${chosenKey}-attack-1`, `./assets/sprites/${chosenKey}-attack-1.png`);
    this.load.image(`${chosenKey}-attack-2`, `./assets/sprites/${chosenKey}-attack-2.png`);
    this.load.image(`${chosenKey}-hit`, `./assets/sprites/${chosenKey}-hit.png`);

    // Street rat (enemy) — shared across all kids.
    this.load.image('rat-idle', './assets/sprites/rat-idle.png');
    this.load.image('rat-walk-1', './assets/sprites/rat-walk-1.png');
    this.load.image('rat-walk-2', './assets/sprites/rat-walk-2.png');
    this.load.image('rat-attack', './assets/sprites/rat-attack.png');
    this.load.image('rat-hit', './assets/sprites/rat-hit.png');

    this.load.image('cockroach-idle', './assets/sprites/cockroach-idle.png');
    this.load.image('cockroach-walk-1', './assets/sprites/cockroach-walk-1.png');
    this.load.image('cockroach-walk-2', './assets/sprites/cockroach-walk-2.png');
    this.load.image('cockroach-attack', './assets/sprites/cockroach-attack.png');
    this.load.image('cockroach-hit', './assets/sprites/cockroach-hit.png');

    // French fries (pickup) — shared.
    this.load.image('fries', './assets/sprites/fries.png');

    // Stage 1 background tiles. Generated by a parallel agent and may not
    // yet exist on disk — track failures in this.missingBg so create() can
    // fall back to colored rectangles without breaking the scene.
    this.missingBg = new Set();
    this.load.on('loaderror', (file) => {
      if (file && typeof file.key === 'string' && file.key.startsWith('bg-stage1-tile')) {
        this.missingBg.add(file.key);
      }
    });
    this.load.image('bg-stage1-tile1', './assets/backgrounds/stage1-tile1.png');
    this.load.image('bg-stage1-tile2', './assets/backgrounds/stage1-tile2.png');
    this.load.image('bg-stage1-tile3', './assets/backgrounds/stage1-tile3.png');

    // Audio (SFX + music). SoundManager registers itself in create(), but the
    // loader calls live here so Phaser has textures/audio ready by create().
    new SoundManager(this).preload();
  }

  create() {
    // SoundManager must be created before the Player so entities can reach it
    // via `this.scene.sound_mgr?.playSfx(...)`. Don't shadow Phaser's built-in
    // `this.sound` — use `sound_mgr`.
    this.sound_mgr = new SoundManager(this);

    this.gameOver = false;
    this.stageCleared = false;
    // Lives + score reset on every fresh BootScene entry (Retry from GameOver
    // goes through CharacterSelect → BootScene, so this runs again).
    this.lives = STARTING_LIVES;
    this.score = 0;
    this._respawning = false;
    this._stageClearPromptShown = false;

    // ── World + camera setup for the side-scrolling stage ───────────────────
    // Physics bounds span the full 3-tile world so player + rats can't walk
    // off the edges. Camera bounds match. Follow the player horizontally
    // with lerp; deadzone lets them wander around the middle 200px before
    // the camera starts panning.
    this.physics.world.setBounds(0, 0, WORLD_WIDTH, WORLD_HEIGHT);
    this.cameras.main.setBounds(0, 0, WORLD_WIDTH, WORLD_HEIGHT);

    // Background tiles (behind everything). Fall back to a dark rectangle
    // per-slot if the generated asset didn't load.
    const fallbackColors = [0x1e1430, 0x241a3a, 0x0f0a1a];
    for (let i = 0; i < 3; i++) {
      const key = `bg-stage1-tile${i + 1}`;
      const x = BG_TILE_WIDTH * i;
      if (this.textures.exists(key) && !this.missingBg?.has(key)) {
        this.add
          .image(x, 0, key)
          .setOrigin(0, 0)
          .setDisplaySize(BG_TILE_WIDTH, BG_TILE_HEIGHT)
          .setDepth(-1000);
      } else {
        this.add
          .rectangle(x, 0, BG_TILE_WIDTH, BG_TILE_HEIGHT, fallbackColors[i])
          .setOrigin(0, 0)
          .setDepth(-1000);
      }
    }

    // Register animations. Idle / hit / rat-attack textures are handled via setTexture
    // on the entity state machines — only walks and the player-attack swing are multi-frame.
    // Player anims keyed by chosenKey so each kid gets their own walk/attack cycle.
    const k = this.chosenKey;
    this.anims.create({
      key: `${k}-walk`,
      frames: [{ key: `${k}-walk-1` }, { key: `${k}-walk-2` }],
      frameRate: 6,
      repeat: -1,
    });
    this.anims.create({
      key: `${k}-attack`,
      frames: [{ key: `${k}-attack-1` }, { key: `${k}-attack-2` }],
      frameRate: 10,
      repeat: 0,
    });
    this.anims.create({
      key: 'rat-walk',
      frames: [{ key: 'rat-walk-1' }, { key: 'rat-walk-2' }],
      frameRate: 4,
      repeat: -1,
    });
    this.anims.create({
      key: 'cockroach-walk',
      frames: [{ key: 'cockroach-walk-1' }, { key: 'cockroach-walk-2' }],
      frameRate: 8,
      repeat: -1,
    });

    // Player — pass the chosen kid so Player pulls the right texture/anim keys
    // and per-character stats (hp, speed, damage, reach) from src/data/characters.js.
    // Spawn on the left edge of the first approach zone so the player walks
    // in rather than starting mid-arena.
    this.player = new Player(this, PLAYER_SPAWN_X, PLAYER_SPAWN_Y, this.chosenKey);

    // Stage / wave / section state.
    this.stage = getStage(0);
    this.sections = this.stage.sections ?? [];
    // A "section" maps 1:1 to a "wave" for HUD purposes, so currentWaveIndex
    // tracks the section index too. currentSectionIndex is the authoritative
    // walker for scroll-camera logic; this.currentWaveIndex mirrors it.
    this.currentSectionIndex = 0;
    this.currentWaveIndex = 0;
    this.enemies = [];
    this.waveTransitioning = false;
    this.sectionActive = false; // true while a battle zone is locked
    this.scrollLockX = null; // camera lock x while sectionActive
    this.scrollLockWall = null; // invisible static body blocking the player

    // Camera: follow the player with a gentle lerp and a wide deadzone so
    // the camera only pans when the player drifts outside the middle band.
    this.cameras.main.startFollow(this.player.sprite, true, CAMERA_LERP_X, 0);
    this.cameras.main.setDeadzone(CAMERA_DEADZONE_W, WORLD_HEIGHT);

    // Pickups (french fries)
    this.pickups = [];

    // Active attack hitboxes
    this.activeHitboxes = [];

    // Input
    this.cursors = this.input.keyboard.createCursorKeys();
    this.keys = {
      attack: this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.Z),
    };

    // HUD — HP, Lives, Score stacked top-left. scrollFactor(0) pins them to
    // the viewport so they don't slide off as the camera pans with the player.
    this.hpText = this.add.text(16, 12, '', {
      fontFamily: 'monospace',
      fontSize: '18px',
      color: '#ffffff',
    }).setDepth(100000).setScrollFactor(0);
    this.updateHpText();

    this.livesText = this.add.text(16, 36, '', {
      fontFamily: 'monospace',
      fontSize: '18px',
      color: '#ffffff',
    }).setDepth(100000).setScrollFactor(0);
    this.updateLivesText();

    this.scoreText = this.add.text(16, 60, '', {
      fontFamily: 'monospace',
      fontSize: '18px',
      color: '#ffd54a',
    }).setDepth(100000).setScrollFactor(0);
    this.updateScoreText();

    // Wave counter HUD (top-right, mirrors HP text style)
    this.waveText = this.add.text(1024 - 16, 12, '', {
      fontFamily: 'monospace',
      fontSize: '18px',
      color: '#ffffff',
    }).setOrigin(1, 0).setDepth(100000).setScrollFactor(0);
    this.updateWaveText();

    // Subtitle + title fixed to viewport so they don't scroll out.
    this.add.text(512, 24, 'Park Slope Heroes', {
      fontFamily: 'monospace',
      fontSize: '22px',
      color: '#ffffff',
    }).setOrigin(0.5).setScrollFactor(0).setDepth(100000);

    this.add.text(512, 48, 'Arrows = move, Z = attack', {
      fontFamily: 'monospace',
      fontSize: '12px',
      color: '#cccccc',
    }).setOrigin(0.5).setScrollFactor(0).setDepth(100000);

    this.gameOverText = null;

    // Stage music starts once the scene is up. Autoplay is already unlocked
    // because CharacterSelect's first-gesture handler ran before we got here.
    this.sound_mgr.startMusic('music_stage1');
  }

  updateHpText() {
    this.hpText.setText(`HP: ${this.player.hp} / ${this.player.maxHp}`);
  }

  updateWaveText() {
    const total = this.stage.waves.length;
    // Display is 1-indexed. Clamp to total so it doesn't show "Wave 4 / 3"
    // during the last-kill frame before stage-clear text appears.
    const display = Math.min(this.currentWaveIndex + 1, total);
    this.waveText.setText(`Wave ${display} / ${total}`);
  }

  updateLivesText() {
    // Unicode hearts read cleanly in the monospace HUD. Fall back to a
    // numeric suffix when lives exceed 3 (shouldn't happen today, but cheap).
    const hearts =
      this.lives >= 0 && this.lives <= 5 ? '❤'.repeat(this.lives) : `x${this.lives}`;
    this.livesText.setText(`LIVES: ${hearts}`);
  }

  updateScoreText() {
    this.scoreText.setText(`SCORE: ${this.score}`);
  }

  addScore(points) {
    this.score += points;
    this.updateScoreText();
  }

  // ── Section / battle zone lifecycle ──────────────────────────────────────

  _activateSection(index) {
    const section = this.sections[index];
    if (!section) return;

    this.sectionActive = true;
    this.currentSectionIndex = index;
    this.currentWaveIndex = index;
    this.scrollLockX = section.cameraLockX;

    // Lock camera: stop follow, pan smoothly to the lock position. Lock
    // position centers `cameraLockX` in the viewport → scrollX = lockX - 512.
    this.cameras.main.stopFollow();
    const targetScrollX = Phaser.Math.Clamp(
      section.cameraLockX - CAMERA_VIEW_HALF,
      0,
      WORLD_WIDTH - 1024,
    );
    this.cameras.main.pan(
      targetScrollX + CAMERA_VIEW_HALF,
      CAMERA_PAN_MS,
      'Sine.easeInOut',
    );

    // Invisible wall at cameraLockX + a bit of slack so the player can close
    // with rats on their side of the lock but not walk past. A static rect
    // with arcade physics does the job.
    const wall = this.add.rectangle(
      section.cameraLockX + 40,
      WORLD_HEIGHT / 2,
      20,
      WORLD_HEIGHT,
      0x000000,
      0, // fully transparent
    );
    this.physics.add.existing(wall, true);
    this.physics.add.collider(this.player.sprite, wall);
    this.scrollLockWall = wall;

    // Spawn rats: one cluster to the right of the lock (ahead of the player)
    // and a smaller cluster to the left (behind, for the "surrounded" feel).
    // Y stays inside the sidewalk band.
    this._spawnSectionEnemies(section);

    this.waveTransitioning = false;
    this.updateWaveText();
  }

  _spawnSectionEnemies(section) {
    const lockX = section.cameraLockX;
    const randY = () => Phaser.Math.Between(SIDEWALK_Y_MIN, SIDEWALK_Y_MAX);

    if (section.rats != null) {
      const count = section.rats;
      const behindCount = Math.max(1, Math.floor(count / 3));
      const aheadCount = count - behindCount;
      for (let i = 0; i < aheadCount; i++) {
        const x = lockX + Phaser.Math.Between(50, 200) + i * 80;
        this.enemies.push(new StreetRat(this, x, randY()));
      }
      for (let i = 0; i < behindCount; i++) {
        const x = section.triggerX - 100 - i * 60;
        this.enemies.push(new StreetRat(this, x, randY()));
      }
      return;
    }

    if (section.roaches != null) {
      const count = section.roaches;
      const behindCount = Math.max(1, Math.floor(count / 3));
      const aheadCount = count - behindCount;
      for (let i = 0; i < aheadCount; i++) {
        const x = lockX + Phaser.Math.Between(50, 200) + i * 60;
        this.enemies.push(new Cockroach(this, x, randY()));
      }
      for (let i = 0; i < behindCount; i++) {
        const x = section.triggerX - 100 - i * 50;
        this.enemies.push(new Cockroach(this, x, randY()));
      }
      return;
    }
  }

  _onSectionCleared() {
    // Destroy the lock wall and resume camera follow. Advance section index.
    if (this.scrollLockWall) {
      this.scrollLockWall.destroy();
      this.scrollLockWall = null;
    }
    this.scrollLockX = null;
    this.sectionActive = false;

    this.cameras.main.startFollow(this.player.sprite, true, CAMERA_LERP_X, 0);

    const banner = this.add.text(512, 288, 'Zone Clear!', {
      fontFamily: 'monospace',
      fontSize: '32px',
      color: '#ffffff',
      backgroundColor: '#000000',
      padding: { x: 16, y: 10 },
    }).setOrigin(0.5).setDepth(100001).setScrollFactor(0);
    this.time.delayedCall(WAVE_CLEAR_TEXT_MS, () => {
      if (banner && banner.scene) banner.destroy();
    });

    const nextIndex = this.currentSectionIndex + 1;
    if (nextIndex >= this.sections.length) {
      // All zones cleared → seal the stage so the final trigger cannot respawn enemies.
      sealFinalSection(this);
      this.time.delayedCall(WAVE_ADVANCE_DELAY_MS, () => {
        if (this.gameOver) return;
        this._onStageCleared();
      });
    } else {
      // Advance the HUD wave indicator to the next (upcoming) zone.
      this.currentSectionIndex = nextIndex;
      this.currentWaveIndex = nextIndex;
      this.waveTransitioning = false;
      this.updateWaveText();
    }
  }

  _onStageCleared() {
    showStageTransition(this, {
      title: 'STAGE 1 CLEAR!',
      subtitle: 'The first block is safe.',
      nextLabel: 'Next: Stage 2 — JJ Byrne Playground',
      onComplete: () => this._goToVictory(),
    });
  }


  _goToVictory() {
    if (this.gameOver) return;
    this.gameOver = true;
    this.sound_mgr?.stopMusic();
    // Stage 1 → Stage 2: carry score + lives forward. Stage 2 picks up where
    // we left off rather than running a fresh game.
    this.scene.start('Stage2', {
      score: this.score,
      lives: this.lives,
    });
  }

  update() {
    if (this.gameOver || this.stageCleared) return;

    // Player update (movement, attack input). Player.attack() registers hitboxes with
    // this.activeHitboxes directly.
    this.player.update(this.cursors, this.keys);

    // Clamp player Y to the sidewalk band (380-490). Y is authoritative on
    // the sprite; body tracks via arcade. Done in-scene so Player.js stays
    // level-agnostic.
    if (this.player.sprite.y < SIDEWALK_Y_MIN) this.player.sprite.y = SIDEWALK_Y_MIN;
    if (this.player.sprite.y > SIDEWALK_Y_MAX) this.player.sprite.y = SIDEWALK_Y_MAX;

    // Trigger-check: if we're NOT in an active section and the player has
    // crossed the next section's triggerX, activate it.
    if (
      !this.sectionActive &&
      !this.stageCleared &&
      this.currentSectionIndex < this.sections.length
    ) {
      const next = this.sections[this.currentSectionIndex];
      if (next && this.player.sprite.x >= next.triggerX) {
        this._activateSection(this.currentSectionIndex);
      }
    }

    // Rat behavior — iterate every live rat
    for (const enemy of this.enemies) {
      if (!enemy.alive) continue;
      enemy.update(this.player);

      // Clamp rat Y to the sidewalk band too so chase AI can't drift them
      // into the skybox.
      if (enemy.sprite.y < SIDEWALK_Y_MIN) enemy.sprite.y = SIDEWALK_Y_MIN;
      if (enemy.sprite.y > SIDEWALK_Y_MAX) enemy.sprite.y = SIDEWALK_Y_MAX;

      // Contact damage: rat overlaps player
      if (
        this.player.alive &&
        !this.player.invulnerable &&
        this._overlap(enemy.sprite, this.player.sprite)
      ) {
        this.player.takeDamage(enemy.contactDamage);
        this.updateHpText();
        this.checkGameOver();
        if (this.gameOver) return;
      }

      // Attack hitboxes vs this rat. hb.hasHit stays single-target — one hitbox
      // can only damage one enemy, so we break out of the hitbox loop as soon as
      // one connects with this rat. Next rat in the outer loop gets its own shot
      // at any remaining not-yet-hit hitboxes.
      for (const hb of this.activeHitboxes) {
        if (!hb || !hb.scene) continue;
        if (hb.hasHit) continue;
        if (this._overlap(hb, enemy.sprite)) {
          hb.hasHit = true;
          enemy.takeDamage(this.player.damage);
          if (!enemy.alive) {
            // Drop fries at kill location
            this.pickups.push(new FrenchFries(this, enemy.x, enemy.y));
            this.addScore(RAT_KILL_SCORE);
          }
          break;
        }
      }
    }

    // Remove dead rats from the active list
    this.enemies = this.enemies.filter((r) => r.alive);

    // Section clear check: only meaningful while a section is active.
    if (
      this.sectionActive &&
      this.enemies.length === 0 &&
      !this.waveTransitioning &&
      !this.stageCleared
    ) {
      this.waveTransitioning = true;
      this._onSectionCleared();
    }

    // Prune destroyed hitboxes
    this.activeHitboxes = this.activeHitboxes.filter((h) => h && h.scene);

    // Pickups: overlap with player
    if (this.player.alive) {
      for (const p of this.pickups) {
        if (p.consumed) continue;
        if (this._overlap(p.sprite, this.player.sprite)) {
          p.consume();
          this.player.heal(FRIES_HEAL);
          this.updateHpText();
        }
      }
      this.pickups = this.pickups.filter((p) => !p.consumed);
    }

    // Depth sort by y
    this.player.sprite.depth = this.player.sprite.y;
    for (const r of this.enemies) {
      if (r.sprite) r.sprite.depth = r.sprite.y;
    }
    for (const p of this.pickups) if (p.sprite) p.sprite.depth = p.sprite.y;
    for (const h of this.activeHitboxes) if (h) h.depth = h.y;
  }

  checkGameOver() {
    if (this.player.hp > 0 || this.gameOver || this._respawning) return;
    // Player just died. Decrement lives.
    this.lives -= 1;
    this.updateLivesText();

    if (this.lives > 0) {
      // Respawn flow — keep the current wave state (rats stay where they are)
      // so the "GET UP!" moment carries some weight.
      this._respawning = true;
      const banner = this.add.text(512, 288, 'GET UP!', {
        fontFamily: 'monospace',
        fontSize: '56px',
        color: '#ffd54a',
        stroke: '#000000',
        strokeThickness: 6,
      }).setOrigin(0.5).setDepth(100001).setScrollFactor(0);

      this.time.delayedCall(GET_UP_TEXT_MS, () => {
        if (banner && banner.scene) banner.destroy();
        this._respawnPlayer();
        this._respawning = false;
      });
      return;
    }

    // No lives left → GameOver
    this.gameOver = true;
    this.sound_mgr?.stopMusic();
    this.scene.start('GameOver', {
      score: this.score,
      chosenChar: this.chosenKey,
      victory: false,
    });
  }

  _respawnPlayer() {
    // Respawn inside the current battle zone if one is active, otherwise at
    // the player's last safe approach position. Either way, inside the
    // sidewalk band.
    const p = this.player;
    const respawnX = this.sectionActive && this.scrollLockX != null
      ? this.scrollLockX - 150
      : Math.max(PLAYER_SPAWN_X, p.sprite.x - 100);
    p.alive = true;
    p.hp = p.maxHp;
    p.invulnerable = false;
    p.attacking = false;
    p.state = 'idle';
    p.sprite.setTexture(`${this.chosenKey}-idle`);
    p.sprite.clearTint();
    p.sprite.setAlpha(1);
    p.sprite.setPosition(respawnX, PLAYER_SPAWN_Y);
    p.sprite.body.setVelocity(0, 0);
    this.updateHpText();
  }

  _overlap(a, b) {
    if (!a || !b || !a.scene || !b.scene) return false;
    // Prefer arcade physics body rect when present — this keeps collision tight for
    // feet-anchored sprites whose visual getBounds() would be far larger than the body.
    const ar = a.body
      ? new Phaser.Geom.Rectangle(a.body.x, a.body.y, a.body.width, a.body.height)
      : a.getBounds();
    const br = b.body
      ? new Phaser.Geom.Rectangle(b.body.x, b.body.y, b.body.width, b.body.height)
      : b.getBounds();
    return Phaser.Geom.Intersects.RectangleToRectangle(ar, br);
  }
}
